
export const romanticLines = [
  "Your smile is the only sunrise my soul needs.",
  "Lost in the infinite galaxy of your eyes.",
  "Every heartbeat whispers a prayer for your happiness.",
  "You are the poetry I never knew I could write.",
  "My soul recognized yours the moment we met.",
  "Your presence is the only gravity I ever want to feel.",
  "A vision of grace that makes the stars look dim.",
  "In the book of my life, you are the only chapter that matters.",
  "Your laughter is the melody my heart dances to.",
  "You are the dream I never want to wake up from.",
  "Eternity is too short to love you as you deserve.",
  "My heart found its home the day it found you.",
  "You are the silence in the noise, the peace in the storm.",
  "Wrapped in your light, the world finally makes sense.",
  "You are the magic I always believed in.",
  "Every path I've taken led me straight to your heart.",
  "Your love is the anchor that keeps me whole.",
  "A masterpiece crafted by the hands of destiny.",
  "You are the reason my soul finally learned to sing.",
  "In your arms, I have everything I ever looked for.",
  "Your beauty is a prayer answered by the universe.",
  "I would choose you in every lifetime, in every world.",
  "You are the spark that turned my darkness into dawn.",
  "Your gaze is the only horizon I ever want to chase.",
  "A love so deep, even the oceans feel shallow.",
  "You are the best thing that has ever been mine.",
  "My devotion to you is as infinite as the sky.",
  "Your touch is a language my soul speaks fluently.",
  "You are the only miracle I will ever need.",
  "In the garden of my thoughts, you are the only bloom.",
  "Your love is the secret I want the whole world to know.",
  "You are the architecture of my every joy.",
  "Every moment with you is a treasure beyond measure.",
  "You are the light that guides me through the deepest night.",
  "My heart is an open letter, and every line is for you.",
  "You are the grace I didn't know I was searching for.",
  "Your presence is a sanctuary for my weary soul.",
  "A single glance from you is worth a thousand lifetimes.",
  "You are the only truth in a world full of shadows.",
  "Your love is the fire that warms my very being.",
  "You are the masterpiece I am honored to adore.",
  "Every breath I take is a silent tribute to your love.",
  "You are the rhythm that keeps my heart beating.",
  "Your soul is the twin my heart was born to find.",
  "You are the gold at the end of every rainbow.",
  "Your love is the wind beneath my every dream.",
  "You are the only star in my private sky.",
  "My adoration for you knows no boundaries or end.",
  "Your smile is the cure for every ache I've ever felt.",
  "You are the destination of my soul's long journey.",
  "Your love is a song I want to play on repeat forever.",
  "You are the only person I want to walk through time with.",
  "Your beauty is a symphony composed of light.",
  "In your eyes, I see my entire future unfolding.",
  "You are the heartbeat of my every aspiration.",
  "Your love is the thread that weaves my life together.",
  "You are the only prayer I ever need to whisper.",
  "Your presence turns even the ordinary into magic.",
  "You are the starlight that dances in my dreams.",
  "Your love is the compass that always leads me home.",
  "You are the most beautiful soul I have ever known.",
  "My heart beats only for the rhythm of your grace.",
  "Your laughter is the spark that lights up my world.",
  "You are the only reason I believe in forever.",
  "Your love is the greatest adventure of my life.",
  "You are the only person who truly knows my heart.",
  "Your beauty is a gift I am grateful for every day.",
  "You are the only light I ever want to follow.",
  "Your love is the sanctuary where I finally belong.",
  "You are the most precious treasure I have ever found.",
  "My devotion to you is as steadfast as the mountains.",
  "Your presence is the only gift I ever want to receive.",
  "You are the only dream that ever truly mattered.",
  "Your love is the spark that ignited my soul.",
  "You are the only miracle I will ever need to see.",
  "Your beauty is a reflection of the light in your soul.",
  "You are the only person I want to share my life with.",
  "Your love is the greatest blessing I have ever received.",
  "You are the only star that shines in my darkness.",
  "Your presence is the only peace I have ever known.",
  "You are the most wonderful thing that ever happened to me.",
  "My love for you is as deep as the deepest sea.",
  "Your laughter is the music that fills my heart with joy.",
  "You are the only person I want to love for all eternity.",
  "Your beauty is a masterpiece that takes my breath away.",
  "You are the only reason my heart beats so fast.",
  "Your love is the spark that makes my life worth living.",
  "You are the only person I want to wake up next to.",
  "Your presence is the only thing I ever want to feel.",
  "You are the most precious gift I have ever been given.",
  "My heart is yours, today, tomorrow, and forever.",
  "Your laughter is the melody that plays in my soul.",
  "You are the only person who can make me smile like this.",
  "Your beauty is a radiant light that illuminates my path.",
  "You are the only reason I believe in true love.",
  "Your love is the greatest treasure I have ever possessed.",
  "You are the only person I want to grow old with.",
  "Your presence is the only miracle I ever want to witness.",
  "You are the most beautiful thing I have ever seen.",
  "Eternity is but a moment when I am with you."
];
